// Central data store for Vision LLC site
// Geo pages, properties, team, and service data

export const COMPANY = {
  name: "Vision LLC",
  phone: "423-573-1022",
  phoneHref: "tel:+14235731022",
  email: "leasing@teamvisionllc.com",
  address: "100 5th St., Suite 2W",
  city: "Bristol",
  state: "TN",
  zip: "37620",
  fullAddress: "100 5th St., Suite 2W, Bristol, TN 37620",
  tagline: "Commercial Real Estate. Executive Advisement. Historic Stewardship.",
  heroLine: "Building the Tri-Cities — One Historic Block at a Time.",
  founded: "2002",
  yearsInBusiness: 20,
  about:
    "Vision LLC is the largest private commercial property owner in Downtown Bristol and an award-winning developer specializing in historic adaptive reuse. With over 20 years of continuous downtown investment, we deliver integrated strategy, leasing, development, and construction to help brands thrive.",
};

export const GEO_PAGES = [
  {
    slug: "bristol-tn",
    city: "Bristol",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Bristol, TN",
    metaTitle: "Commercial Real Estate Bristol TN | Vision LLC",
    metaDescription:
      "Vision LLC is Bristol TN's largest private commercial property owner. Find office space, storefronts & warehouse space in Downtown Bristol. Call 423-573-1022.",
    heroSubline: "The #1 Commercial Property Owner in Downtown Bristol",
    lat: 36.5951,
    lng: -82.1887,
    zipCode: "37620",
    countyName: "Sullivan County",
    neighborhoods: ["Downtown Bristol", "State Street", "The Pinnacle District", "Fairmount"],
    nearbyHighways: ["I-81", "US-11E", "US-19W", "TN-394"],
    population: "43,000",
    medianIncome: "$38,000",
    keyEmployers: ["Ballad Health", "Tennessee Eastman", "Bristol Motor Speedway", "King University"],
    marketBlurb:
      "Bristol sits on the Tennessee-Virginia state line, offering businesses a rare dual-state advantage with zip code 37620. As the anchor city of the Tri-Cities MSA, Downtown Bristol is experiencing a powerful urban revival — driven by adaptive reuse, new retail, and hospitality investment along State Street and the Pinnacle District.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse", "CoWorking"],
    isPrimary: true,
  },
  {
    slug: "kingsport-tn",
    city: "Kingsport",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Kingsport, TN",
    metaTitle: "Commercial Real Estate Kingsport TN | Vision LLC",
    metaDescription:
      "Kingsport, TN businesses: Vision LLC connects you with premium commercial space in Downtown Bristol, a short drive via I-26. Office, retail & industrial options across the Tri-Cities. Call 423-573-1022.",
    heroSubline: "Commercial Property Solutions Serving Kingsport & the Tri-Cities",
    lat: 36.5484,
    lng: -82.5618,
    zipCode: "37660",
    countyName: "Sullivan County",
    neighborhoods: ["Center City", "Kingsport Town Center", "Riverview", "Eastman Road Corridor"],
    nearbyHighways: ["I-26", "US-11W", "TN-36", "TN-126"],
    population: "55,000",
    medianIncome: "$44,000",
    keyEmployers: ["Eastman Chemical", "Holston Valley Medical", "Domtar", "BAE Systems"],
    marketBlurb:
      "Kingsport (zip 37660) is the industrial powerhouse of the Tri-Cities, anchored by Eastman Chemical — one of the world's largest specialty chemical companies. The Center City district is undergoing major reinvention along the I-26 corridor, creating prime commercial real estate opportunities for office and retail tenants.",
    availableTypes: ["Office", "Retail Storefront", "Industrial/Warehouse"],
    isPrimary: false,
  },
  {
    slug: "johnson-city-tn",
    city: "Johnson City",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Johnson City, TN",
    metaTitle: "Commercial Real Estate Johnson City TN | Vision LLC",
    metaDescription:
      "Johnson City, TN businesses: Vision LLC connects you with commercial real estate in Downtown Bristol, TN. Office, retail & mixed-use options across the Tri-Cities. Call 423-573-1022.",
    heroSubline: "Office Space & Commercial Properties Serving Johnson City",
    lat: 36.3134,
    lng: -82.3535,
    zipCode: "37601",
    countyName: "Washington County",
    neighborhoods: ["Downtown Johnson City", "State of Franklin", "University District", "North Side"],
    nearbyHighways: ["I-26", "US-321", "TN-381", "TN-67"],
    population: "71,000",
    medianIncome: "$40,000",
    keyEmployers: ["ETSU", "Ballad Health", "Domtar", "Carilion Clinic"],
    marketBlurb:
      "Johnson City (zip 37601) is the largest city in the Tri-Cities and home to East Tennessee State University. The Downtown and State of Franklin districts along I-26 are rapidly evolving — making this an ideal market for retail, professional office, and mixed-use commercial investment.",
    availableTypes: ["Office", "Retail Storefront", "Mixed-Use"],
    isPrimary: false,
  },
  {
    slug: "abingdon-va",
    city: "Abingdon",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Abingdon, VA",
    metaTitle: "Commercial Real Estate Abingdon VA | Vision LLC",
    metaDescription:
      "Abingdon, VA businesses: Vision LLC connects you with commercial real estate in Downtown Bristol, TN — just 20 min on I-81. Office & retail options at the TN/VA state line. Call 423-573-1022.",
    heroSubline: "Virginia Commercial Real Estate — Just Across the State Line",
    lat: 36.7098,
    lng: -81.9774,
    zipCode: "24210",
    countyName: "Washington County",
    neighborhoods: ["Main Street Abingdon", "Old Town", "Downtown Abingdon", "Wolf Hills"],
    nearbyHighways: ["I-81", "US-11", "US-58A", "VA-75"],
    population: "9,200",
    medianIncome: "$48,000",
    keyEmployers: ["Virginia Highlands Community College", "Johnston Memorial Hospital", "Washington County Schools"],
    marketBlurb:
      "Abingdon (zip 24210) is the seat of Washington County, VA — a historic town just 20 minutes from Bristol on I-81. Known for the Barter Theatre and Virginia Creeper Trail, Abingdon's Main Street district offers boutique commercial real estate in one of Virginia's most charming small cities.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "elizabethton-tn",
    city: "Elizabethton",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Elizabethton, TN",
    metaTitle: "Commercial Real Estate Elizabethton TN | Vision LLC",
    metaDescription:
      "Elizabethton, TN businesses: Vision LLC connects you with commercial space in Downtown Bristol. Serving Carter County & Northeast Tennessee. Call 423-573-1022.",
    heroSubline: "Commercial Opportunities in Carter County & Elizabethton",
    lat: 36.3487,
    lng: -82.2107,
    zipCode: "37643",
    countyName: "Carter County",
    neighborhoods: ["Downtown Elizabethton", "Riverside", "Doe River Corridor", "Hampton"],
    nearbyHighways: ["TN-91", "TN-19E", "US-321", "TN-67"],
    population: "14,000",
    medianIncome: "$35,000",
    keyEmployers: ["Elizabethton City Schools", "Sycamore Shoals Hospital", "Carter County Government"],
    marketBlurb:
      "Elizabethton (zip 37643) in Carter County offers affordable commercial real estate with immediate access to the Johnson City metro via US-321. The Doe River corridor and downtown district are attracting new dining and retail concepts seeking lower overhead while maintaining access to the broader Tri-Cities consumer base.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
  {
    slug: "gate-city-va",
    city: "Gate City",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Gate City, VA",
    metaTitle: "Commercial Real Estate Gate City VA | Vision LLC",
    metaDescription:
      "Gate City, VA businesses: Vision LLC connects you with commercial real estate in Downtown Bristol, TN — accessible via US-23. Serving Scott County & Southwest Virginia. Call 423-573-1022.",
    heroSubline: "Scott County Commercial Real Estate Near the Bristol Market",
    lat: 36.6323,
    lng: -82.5779,
    zipCode: "24251",
    countyName: "Scott County",
    neighborhoods: ["Downtown Gate City", "Duffield", "Weber City", "Clinchport"],
    nearbyHighways: ["US-23", "US-58A", "VA-71", "VA-72"],
    population: "2,200",
    medianIncome: "$32,000",
    keyEmployers: ["Scott County Schools", "Mountain Empire Community College", "Lonesome Pine Hospital"],
    marketBlurb:
      "Gate City (zip 24251) serves as the commercial hub of Scott County, VA — a growing market 35 minutes from Bristol along the US-23 corridor. With low overhead and proximity to the Tri-Cities labor pool, Gate City attracts businesses seeking affordable commercial space with strong Southwest Virginia market access.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "blountville-tn",
    city: "Blountville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Blountville, TN",
    metaTitle: "Commercial Real Estate Blountville TN | Vision LLC",
    metaDescription:
      "Blountville, TN businesses: Vision LLC connects you with commercial space in Downtown Bristol. Serving Sullivan County near Tri-Cities Airport. Call 423-573-1022.",
    heroSubline: "Sullivan County Commercial Real Estate Near Tri-Cities Airport",
    lat: 36.5292,
    lng: -82.3296,
    zipCode: "37617",
    countyName: "Sullivan County",
    neighborhoods: ["Airport District", "Blountville Commons", "Tri-Cities Regional", "Old Jonesboro Road"],
    nearbyHighways: ["I-26", "I-81", "TN-394", "US-11W"],
    population: "12,000",
    medianIncome: "$42,000",
    keyEmployers: ["Tri-Cities Regional Airport", "Sullivan County Government", "NiSource / Columbia Gas"],
    marketBlurb:
      "Blountville (zip 37617) is strategically located at the I-26/I-81 interchange — the economic crossroads of the Tri-Cities. Anchored by Tri-Cities Regional Airport and Sullivan County government, this market offers prime industrial, office, and logistics commercial real estate with unmatched regional highway access.",
    availableTypes: ["Office", "Industrial/Warehouse", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "greeneville-tn",
    city: "Greeneville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Northeast Tennessee",
    h1: "Commercial Real Estate in Greeneville, TN",
    metaTitle: "Commercial Real Estate Greeneville TN | Vision LLC",
    metaDescription:
      "Greeneville, TN businesses: Vision LLC connects you with commercial space in Downtown Bristol. Serving Greene County & Northeast Tennessee. Call 423-573-1022.",
    heroSubline: "Greene County Commercial Real Estate & Business Consulting",
    lat: 36.1637,
    lng: -82.8318,
    zipCode: "37743",
    countyName: "Greene County",
    neighborhoods: ["Downtown Greeneville", "Tusculum", "Camp Creek", "Five Points"],
    nearbyHighways: ["US-11E", "TN-70", "TN-351", "TN-172"],
    population: "15,000",
    medianIncome: "$37,000",
    keyEmployers: ["Tusculum University", "Laughlin Memorial Hospital", "General Shale"],
    marketBlurb:
      "Greeneville (zip 37743) is Greene County's seat of commerce — a historic city anchored by Tusculum University and a growing manufacturing sector along the US-11E corridor. Just 45 minutes from the Tri-Cities, Greeneville offers exceptional commercial real estate value for retail, office, and light industrial tenants.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
];


export const PROPERTIES = [
  {
    id: "city-centre",
    name: "City Centre Professional Suites",
    type: "Office",
    city: "Bristol, TN",
    address: "100 5th St., Bristol, TN 37620",
    sqft: "120 – 6,000",
    status: "Available",
    badge: "Featured",
    badgeColor: "green",
    image: "/property-images/city-centre-1.jpg",
    images: [
      "/property-images/city-centre-1.jpg",
      "/property-images/city-centre-2.jpg",
      "/property-images/city-centre-3.jpg",
    ],
    description:
      "City Centre Professional Suites is the Preservation Award-winning office address in the heart of Downtown Bristol — The Birthplace of Country Music. We offer premier office suites from 120 to 6,000 sqft with a professional environment that makes a great first impression on clients and business associates. All-inclusive pricing covers power, water, common area cleaning, security cameras, property taxes, fitness access, and maintenance. No hidden costs. Single offices also available. It's the best deal in the Tri-Cities.",
    features: [
      "120 – 6,000 sqft Suites",
      "All-Inclusive Pricing",
      "No Hidden Costs",
      "CCTV Security",
      "Fitness Access",
      "Preservation Award Winner",
      "Downtown Bristol",
      "Single Offices Available",
    ],
    imageAlt: "City Centre Professional Suites 100 5th Street Downtown Bristol TN",
  },
  {
    id: "bristol-cowork",
    name: "Bristol CoWork",
    type: "CoWorking",
    city: "Bristol, TN",
    address: "620 State Street, Bristol, TN",
    sqft: "5,000+",
    status: "Memberships Available",
    badge: "CoWork",
    badgeColor: "gold",
    image: "/property-images/cowork-shared-office.jpg",
    images: [
      "/property-images/cowork-shared-office.jpg",
      "/property-images/cowork-conference-room.jpg",
      "/property-images/cowork-lobby-waiting.jpg",
      "/property-images/cowork-private-office.jpg",
    ],
    description:
      "Experience modern commercial leasing at Bristol CoWork — a 5,000+ sqft facility at 620 State Street offering fully furnished private offices, dedicated desks, and equipped conference rooms with high-speed internet and all utilities included, engineered to support business growth in Bristol TN's commercial real estate market.",
    features: ["Private Offices", "Dedicated Desks", "Conference Rooms", "High-Speed Internet", "Fully Furnished"],
    imageAlt: "Bristol CoWork shared workspace at 620 State Street Bristol Tennessee",
  },
  {
    id: "the-executive",
    name: "The Executive — Premier Office Suites",
    type: "Office",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "500 – 12,000",
    status: "Available",
    badge: "Premium",
    badgeColor: "green",
    image: "/property-images/the-executive-1.jpg",
    images: [
      "/property-images/the-executive-1.jpg",
      "/property-images/the-executive-2.jpg",
      "/property-images/the-executive-3.jpg",
    ],
    description:
      "Discover premier office suites within a meticulously restored historic building — prime Downtown Bristol commercial space ideal for professional services and law firms. The Executive features full-service amenities including a professional address and on-demand meeting rooms, with flexible lease terms from 500–12,000 sqft for businesses that demand a distinguished Tri-Cities presence.",
    features: ["Historic Building", "Full-Service Amenities", "Professional Address", "Flexible Leasing"],
    imageAlt: "The Executive premier office suite entry in Downtown Bristol TN",
  },
  {
    id: "centre-point-suites",
    name: "Centre Point",
    type: "Retail / Restaurant / Development",
    city: "Bristol, VA",
    address: "Bristol, VA — Across from Hard Rock Hotel & Casino",
    sqft: "Varies by Unit",
    status: "Units Available",
    badge: "Casino Adjacent",
    badgeColor: "green",
    image: "/property-images/centre-point-1.jpg",
    images: [
      "/property-images/centre-point-1.jpg",
      "/property-images/centre-point-2.jpg",
      "/property-images/centre-point-3.jpg",
    ],
    description:
      "Position your business for unparalleled success at Centre Point — a premier commercial property development directly across from the Hard Rock Hotel & Casino in Bristol, VA. This is the epicenter of the region's most significant economic transformation. With the casino as your neighbor, you'll benefit from a constant flow of high-traffic, high-value clientele. Whether you are looking to build a restaurant, retail space, beauty services, or any other venture, Centre Point provides the perfect blank canvas with commercial zoning and a front-row seat to Bristol's explosive growth.",
    features: [
      "Hard Rock Casino Adjacent",
      "High-Traffic Clientele",
      "Restaurant Ready",
      "Retail & Service Zoning",
      "Tourism & Entertainment Hub",
      "Bristol, VA Location",
      "Blank Canvas Build-Out",
      "Prime Investment Opportunity",
    ],
    imageAlt: "Centre Point commercial property across from Hard Rock Hotel Casino Bristol VA",
  },
  {
    id: "foundation-event-facility",
    name: "Foundation Event Facility",
    type: "Event Space / Venue",
    city: "Bristol, TN",
    address: "620 State Street, Bristol, TN 37620",
    sqft: "3 Distinct Venues",
    status: "Available",
    badge: "Unique",
    badgeColor: "gold",
    image: "/property-images/foundation-event-1.jpg",
    images: [
      "/property-images/foundation-event-1.jpg",
      "/property-images/foundation-event-2.jpg",
      "/property-images/foundation-event-3.jpg",
    ],
    description:
      "Make your next event truly unforgettable at The Foundation Event Facility — the premier event venue in the Tri-Cities. Located at 620 State Street in Downtown Bristol, we offer 3 distinct rooms accommodating anywhere from 15 to 100 guests at an affordable price. Perfect for baby showers, wedding showers, seminars, live music, fundraisers, business functions, class reunions, company holiday parties, private parties, and galas. Vision LLC manages the food, the venue, and every detail.",
    features: [
      "3 Distinct Venues",
      "15 to 100 Guests",
      "620 State Street",
      "Baby & Wedding Showers",
      "Corporate Events",
      "Live Music",
      "Galas & Private Parties",
      "Full-Service Coordination",
    ],
    imageAlt: "Foundation Event Facility 620 State Street Downtown Bristol TN event venue",
  },
  {
    id: "west-state-commons",
    name: "West State Commons — Offices & Warehouse",
    type: "Mixed-Use / Industrial",
    city: "Bristol, VA",
    address: "1916 West State Street, Bristol, VA 24201",
    sqft: "8,000 Office + 45,500 Warehouse",
    status: "Available",
    badge: "Industrial",
    badgeColor: "gold",
    image: "/property-images/west-state-commons-1.jpg",
    images: [
      "/property-images/west-state-commons-1.jpg",
      "/property-images/west-state-commons-2.jpg",
      "/property-images/west-state-commons-3.jpg",
    ],
    description:
      "Formerly owned by Coca-Cola, West State Commons is a landmark opportunity property at 1916 West State Street in Bristol, VA. The building features 8,000 sqft of commercial office space alongside over 45,500 sqft of tractor-trailer accessible warehouse space with 26-foot ceilings. Loading docks are situated along the rear, and Vision LLC is open to sub-dividing to suit your footprint needs. A truly unique property located in the heart of Bristol, VA.",
    features: [
      "8,000 sqft Office Space",
      "45,500+ sqft Warehouse",
      "26-Foot Ceilings",
      "Loading Docks",
      "Tractor-Trailer Accessible",
      "Sub-Division Available",
      "Bristol, VA Location",
      "Former Coca-Cola Facility",
    ],
    imageAlt: "West State Commons 1916 West State Street Bristol VA — former Coca-Cola warehouse",
  },
  {
    id: "815-shelby-street",
    name: "Jamestown at Shelby",
    type: "Professional Office Suites",
    city: "Bristol, TN",
    address: "815 Shelby Street, Bristol, TN 37620",
    sqft: "1,200 – 4,500",
    status: "Limited Availability",
    badge: "Office",
    badgeColor: "green",
    image: "/property-images/jamestown-shelby-1.jpg",
    images: [
      "/property-images/jamestown-shelby-1.jpg",
      "/property-images/jamestown-shelby-2.jpg",
      "/property-images/jamestown-shelby-3.jpg",
    ],
    description:
      "Jamestown at Shelby has breathed a new vitality into a part of Bristol's history. With meticulous attention to detail, this property offers an unheard level of professionalism within a unique environment in Bristol. From the ease of off-street parking to convenient access to the heart of downtown, a statement is made to clients and employees alike — from the moment they enter the building, they will know your company is the right choice. Suites range from 1,200 to 4,500 sqft with no extra CAM fees; all common areas are managed by Vision LLC at no additional cost.",
    features: [
      "1,200 – 4,500 sqft Suites",
      "No CAM Fees",
      "Off-Street Parking",
      "CCTV Security System",
      "Common Areas Managed",
      "Downtown Bristol Access",
      "Flexible Floor Plans",
      "Limited Units Remaining",
    ],
    imageAlt: "Jamestown at Shelby professional office suites 815 Shelby Street Bristol TN",
  },
  {
    id: "250-commonwealth-ave",
    name: "250 Commonwealth Ave",
    type: "Office / Commercial",
    city: "Bristol, VA",
    address: "250 Commonwealth Ave, Bristol, VA",
    sqft: "TBD",
    status: "Available",
    badge: "Virginia Side",
    badgeColor: "gold",
    image: "/property-images/250-commonwealth-1.jpg",
    images: [
      "/property-images/250-commonwealth-1.jpg",
      "/property-images/250-commonwealth-2.jpg",
      "/property-images/250-commonwealth-3.jpg",
    ],
    description:
      "250 Commonwealth Ave is a prominent commercial property on the Virginia side of Bristol — offering flexible office and commercial space at a highly accessible address with excellent visibility. This property presents a rare opportunity for businesses seeking a dual-state presence in the Bristol TN/VA market, with Vision LLC's full leasing and property management support. Contact us for availability and current pricing.",
    features: ["Virginia Address", "High Visibility", "Dual-State Market Access", "Professional Space"],
    imageAlt: "250 Commonwealth Ave commercial office space Bristol VA",
  },
  {
    id: "628-state-street",
    name: "628 State Street",
    type: "Restaurant / Retail / Event",
    city: "Bristol, TN",
    address: "628 State Street, Bristol, TN",
    sqft: "8,500",
    status: "For Lease",
    badge: "State Street",
    badgeColor: "green",
    image: "/property-images/628-state-street-1.jpg",
    images: [
      "/property-images/628-state-street-1.jpg",
      "/property-images/628-state-street-2.jpg",
      "/property-images/628-state-street-3.jpg",
    ],
    description:
      "628 State Street is a rare 8,500 sqft opportunity in the heart of Downtown Bristol, Tennessee — The Birthplace of Country Music. Featuring a dramatic open floor plan, a full bar, commercial kitchen, mezzanine level, and dedicated office space, this property is turnkey for a restaurant, entertainment venue, flagship retail concept, or a fully custom build-out. Positioned on Bristol's most iconic commercial corridor at the Tennessee-Virginia state line, 628 State Street delivers unmatched foot traffic, cultural cachet, and the energy of a downtown district on the rise.",
    features: [
      "8,500 sqft Open Floor Plan",
      "Full Bar",
      "Commercial Kitchen",
      "Mezzanine Level",
      "Office Space",
      "State Street Frontage",
      "Restaurant / Venue Ready",
      "Custom Build-Out Available",
    ],
    imageAlt: "628 State Street restaurant and event space Downtown Bristol TN — Birthplace of Country Music",
  },
];

export const STATS = [
  { value: "20+", label: "Years in the Tri-Cities" },
  { value: "#1", label: "Largest Private CRE Owner in Downtown Bristol" },
  { value: "50+", label: "Commercial Properties Managed" },
  { value: "3", label: "Integrated Business Divisions" },
];

export const TESTIMONIALS = [
  {
    quote:
      "Vision LLC transformed our understanding of the Bristol market. Allen's team didn't just find us a space — they positioned us for long-term success in the region. Exceptional advisement.",
    author: "Regional Business Owner",
    location: "Bristol, TN",
    rating: 5,
  },
  {
    quote:
      "Bristol CoWork gave our startup the professional environment we needed without the overhead of a traditional lease. The team at Vision is genuinely invested in your success.",
    author: "Tech Startup Founder",
    location: "Tri-Cities, TN/VA",
    rating: 5,
  },
  {
    quote:
      "The executive advisement division is unlike anything I've experienced. J. Allen Hurley brings 30 years of real leadership to the table — strategy, not just platitudes.",
    author: "C-Suite Executive",
    location: "Johnson City, TN",
    rating: 5,
  },
];

export const SERVICES = [
  {
    id: "leasing",
    icon: "Building2",
    title: "Commercial Leasing",
    shortDesc: "Office, retail, warehouse & coworking across the Tri-Cities",
    description:
      "From intimate storefronts to large-format warehouse space, Vision LLC offers the most diverse commercial leasing portfolio in downtown Bristol. Our team matches tenants with the right space, the right terms, and the right market positioning.",
    bullets: [
      "Downtown office suites",
      "State Street retail storefronts",
      "Warehouse & industrial space",
      "Bristol CoWork memberships",
    ],
  },
  {
    id: "development",
    icon: "Hammer",
    title: "Development & Construction",
    shortDesc: "Adaptive reuse and ground-up commercial development",
    description:
      "Vision specializes in historic adaptive reuse — restoring Bristol's architectural heritage while creating modern, functional commercial spaces. Our vertically integrated model means we control strategy, design, construction, and leasing under one roof.",
    bullets: [
      "Historic adaptive reuse",
      "Ground-up commercial development",
      "Tenant improvement build-outs",
      "Long-term ownership & stewardship",
    ],
  },
  {
    id: "advisement",
    icon: "TrendingUp",
    title: "Executive Advisement",
    shortDesc: "Strategic leadership consulting for C-suite and corporate teams",
    description:
      "CEO J. Allen Hurley brings 30+ years of executive experience to provide unfiltered, results-driven advisement for corporations, government agencies, and emerging businesses. Not coaching — real strategy.",
    bullets: [
      "C-suite strategic consulting",
      "Corporate performance optimization",
      "Government agency advisement",
      "Leadership development",
    ],
  },
];

export const SPACE_TYPE_PAGES = [
  {
    slug: "coworking-space-bristol-tn",
    type: "CoWorking",
    propertyIds: ["bristol-cowork", "city-centre"],
    h1: "CoWorking Space in Bristol, TN",
    metaTitle: "CoWorking Space Bristol TN | Flexible Offices & Shared Workspaces | Vision LLC",
    metaDescription: "Find coworking space & shared office in Bristol, TN. Bristol CoWork at 620 State Street offers private offices, dedicated desks & conference rooms. Vision LLC — 423-573-1022.",
    tagline: "Flexible Workspace for Modern Businesses",
    accentColor: "#4ADE80",
    badge: "CoWork",
    intro: "Bristol CoWork at 620 State Street is the Tri-Cities' premier flexible workspace — engineered for startups, freelancers, remote teams, and growing businesses that need professional infrastructure without the overhead of a traditional lease.",
    benefits: [
      { icon: "⚡", title: "All-Inclusive Pricing", body: "One flat monthly rate covers utilities, internet, cleaning, and common areas. No surprise bills." },
      { icon: "🔑", title: "Month-to-Month Flexibility", body: "Scale up or down without break clauses. Grow your footprint as your team grows." },
      { icon: "📍", title: "Prime State Street Location", body: "A prestigious Bristol, TN business address at 620 State Street — the heart of Downtown." },
      { icon: "🤝", title: "Built-In Business Community", body: "Network with fellow founders, consultants, and professionals in the same space every day." },
    ],
    faqs: [
      { q: "How much does coworking space cost in Bristol, TN?", a: "Bristol CoWork by Vision LLC offers flexible membership plans starting with hot-desk access through to private fully-furnished offices. Contact us at 423-573-1022 for current pricing." },
      { q: "Does Bristol CoWork offer private offices?", a: "Yes — we offer private lockable office suites as well as dedicated desks and open coworking memberships. All options include high-speed internet, printing, and conference room access." },
      { q: "Can I use Bristol CoWork as my business address?", a: "Absolutely. All Bristol CoWork members receive a professional 620 State Street, Bristol TN business address for mail, registration, and client-facing materials." },
      { q: "Is coworking a good option for remote workers in the Tri-Cities?", a: "It's ideal. Remote workers get structure, reliable internet, a professional environment, and networking opportunities — without the cost or commitment of a private lease." },
      { q: "Do you offer day passes or trial memberships?", a: "Yes — reach out to our team at 423-573-1022 or leasing@teamvisionllc.com to arrange a tour and trial day." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/coworking-space-bristol-tn",
    geoLinks: ["bristol-tn", "kingsport-tn", "johnson-city-tn"],
  },
  {
    slug: "office-space-tri-cities-tn",
    type: "Office",
    propertyIds: ["the-executive", "city-centre", "centre-point-suites"],
    h1: "Office Space for Lease in the Tri-Cities, TN",
    metaTitle: "Office Space Tri-Cities TN | Bristol, Kingsport & Johnson City | Vision LLC",
    metaDescription: "Premium office space for lease in Bristol TN, Kingsport TN & Johnson City TN. Vision LLC manages 50+ commercial properties across the Tri-Cities. Call 423-573-1022.",
    tagline: "Professional Office Suites from 500 to 18,000+ sqft",
    accentColor: "#4ADE80",
    badge: "Office",
    intro: "From intimate 500 sqft professional suites to full-floor executive offices spanning 18,000+ sqft, Vision LLC manages the most diverse office portfolio in the Tri-Cities. Whether you're in Bristol, Kingsport, or Johnson City — we have the right space, at the right price.",
    benefits: [
      { icon: "🏛️", title: "Historic Premium Buildings", body: "Occupy a meticulously restored Downtown Bristol landmark. Brand-defining spaces that no suburban office park can match." },
      { icon: "📐", title: "Flexible Unit Sizes", body: "500 sqft to 18,000+ sqft — expand or consolidate within our portfolio as your company evolves." },
      { icon: "🅿️", title: "Dedicated Parking", body: "Multiple Vision LLC properties offer private tenant parking — a premium in Downtown Bristol's commercial core." },
      { icon: "🔧", title: "Full-Service & Gross Leases", body: "We offer modified gross leases with predictable monthly costs. No hidden fees. Real transparency." },
    ],
    faqs: [
      { q: "How much does office space cost to lease in Bristol, TN?", a: "Office lease rates in Bristol TN vary by building class, size, and amenities. Vision LLC offers competitive rates across our Downtown Bristol portfolio — contact us at 423-573-1022." },
      { q: "What is the difference between a private office and coworking?", a: "A private office is a dedicated, lockable suite under a traditional lease (typically 12–36 months). Coworking offers month-to-month flexibility in a shared environment." },
      { q: "Do you offer office space outside of Bristol, TN?", a: "Vision LLC's primary office inventory is in Downtown Bristol. We can also connect clients with space in Kingsport TN, Johnson City TN, and Abingdon VA through our regional network." },
      { q: "Are Vision LLC office spaces pet-friendly?", a: "Policies vary by building. Contact our leasing team at 423-573-1022 to discuss specific requirements." },
      { q: "Can I get a professional office address in Bristol TN without a full lease?", a: "Yes — Bristol CoWork memberships at 620 State Street include a professional business address without requiring a traditional office lease." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/office-space-tri-cities-tn",
    geoLinks: ["bristol-tn", "kingsport-tn", "johnson-city-tn"],
  },
  {
    slug: "retail-space-bristol-tn",
    type: "Retail / Office",
    propertyIds: ["centre-point-suites", "city-centre", "foundation-event-facility"],
    h1: "Retail Space for Lease in Bristol, TN",
    metaTitle: "Retail Space Bristol TN | Downtown Storefronts & High-Traffic Commercial | Vision LLC",
    metaDescription: "Retail space for lease in Bristol TN. Vision LLC offers downtown storefronts, street-level retail & high-traffic commercial units in Bristol's most sought-after locations. Call 423-573-1022.",
    tagline: "High-Visibility Storefronts in Bristol's Best Corridors",
    accentColor: "#FACC15",
    badge: "Retail",
    intro: "Bristol's retail landscape is experiencing a powerful revival — driven by new hospitality, tourism, and urban investment along State Street and the Pinnacle District. Vision LLC's street-level retail portfolio puts your brand in front of Bristol's most active commercial traffic corridors.",
    benefits: [
      { icon: "📍", title: "Downtown Location", body: "Street-level visibility in Downtown Bristol — where foot traffic, local press, and destination shoppers converge daily." },
      { icon: "🚦", title: "Highest-Traffic Corridors", body: "Centre Point Suites and City Centre sit on Bristol's most-visited commercial streets — with abundant signage opportunities." },
      { icon: "🏪", title: "800 to 18,000+ sqft", body: "Intimate boutique units to large-format anchor retail — we'll match lease size to your concept and business plan." },
      { icon: "🅿️", title: "Ample Customer Parking", body: "Dedicated tenant and customer parking at multiple Vision LLC properties — a critical advantage for retail conversion." },
    ],
    faqs: [
      { q: "Where is the best retail location in Downtown Bristol TN?", a: "State Street and the Pinnacle District are Bristol's retail hot spots. Vision LLC owns multiple properties along these corridors." },
      { q: "How much does retail space cost to lease in Bristol TN?", a: "Retail lease rates depend on location, size, and condition. Contact our leasing team at 423-573-1022 for current availability and pricing." },
      { q: "Does Vision LLC work with restaurant or food & beverage concepts?", a: "Yes — we have experience leasing to F&B concepts and can discuss build-out allowances and modified lease structures to support hospitality tenants." },
      { q: "What retail spaces are available near State Street Bristol?", a: "Vision LLC currently has street-level retail units available at City Centre Professional Suites and Centre Point Suites. Contact us to arrange a tour." },
      { q: "Can Vision LLC help me with a retail build-out in Bristol TN?", a: "Absolutely. Our vertically integrated model includes construction and tenant improvement services — making Vision LLC your single point of contact from lease to launch." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/retail-space-bristol-tn",
    geoLinks: ["bristol-tn", "johnson-city-tn"],
  },
  {
    slug: "industrial-space-tri-cities-tn",
    type: "Industrial",
    propertyIds: ["west-state-commons"],
    h1: "Warehouse & Industrial Space in the Tri-Cities, TN",
    metaTitle: "Warehouse & Industrial Space Tri-Cities TN | Bristol, Kingsport | Vision LLC",
    metaDescription: "Warehouse & industrial space for lease in the Tri-Cities TN. 2,000–25,000 sqft with loading docks, 3-phase power & direct I-81/I-26 highway access. Call Vision LLC: 423-573-1022.",
    tagline: "Flexible Industrial & Warehouse Space with Highway Access",
    accentColor: "#FACC15",
    badge: "Industrial",
    intro: "Vision LLC's industrial and warehouse portfolio provides flexible light industrial, distribution, and manufacturing space across the Bristol, TN metro area — with direct access to the I-81/I-26 interchange, the logistics crossroads of the entire Tri-Cities region.",
    benefits: [
      { icon: "🚛", title: "Loading Dock Access", body: "Drive-in and dock-high loading configurations available — supporting distribution, logistics, and manufacturing operations." },
      { icon: "⚡", title: "3-Phase Power Available", body: "Heavy industrial power supply for manufacturing, data, and equipment-intensive businesses." },
      { icon: "🛣️", title: "I-81 / I-26 Interchange", body: "Minutes from the region's primary highway interchange — ideal for regional distribution and supply chain operations." },
      { icon: "📐", title: "2,000 – 25,000 sqft", body: "Scalable industrial units from small contractor bays to full-scale warehouse operations — with room to grow." },
    ],
    faqs: [
      { q: "What size warehouse spaces are available in Bristol TN?", a: "Vision LLC's Commercial Warehouse Space offers flexible industrial units from 2,000 to 25,000 sqft across the Bristol TN metro area." },
      { q: "Do your industrial spaces have loading docks?", a: "Yes — our warehouse properties include dock-high and drive-in loading configurations. Contact us at 423-573-1022 to discuss specific loading requirements." },
      { q: "Is 3-phase power available in Vision LLC industrial properties?", a: "3-phase electrical service is available in qualifying units. Discuss power requirements with our leasing team during your consultation." },
      { q: "How close are you to I-81 and I-26?", a: "Our Bristol TN industrial properties have direct access to I-81 and the I-26 interchange — the primary logistics corridor for the entire Tri-Cities region." },
      { q: "Can I lease warehouse space month-to-month in the Tri-Cities?", a: "Lease terms are negotiable. Short-term and flexible warehouse leases may be available depending on inventory. Contact our team for current options." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/industrial-space-tri-cities-tn",
    geoLinks: ["bristol-tn", "kingsport-tn"],
  },
];
