// Central data store for Vision LLC site
// Geo pages, properties, team, and service data

export const COMPANY = {
  name: "Vision LLC",
  phone: "423-573-1022",
  phoneHref: "tel:+14235731022",
  email: "leasing@teamvisionllc.com",
  address: "100 5th St., Suite 2W",
  city: "Bristol",
  state: "TN",
  zip: "37620",
  fullAddress: "100 5th St., Suite 2W, Bristol, TN 37620",
  tagline: "Commercial Real Estate. Executive Advisement. Historic Stewardship.",
  heroLine: "Building the Tri-Cities — One Historic Block at a Time.",
  founded: "2002",
  yearsInBusiness: 20,
  about:
    "Vision LLC is the largest private commercial property owner in Downtown Bristol and an award-winning developer specializing in historic adaptive reuse. With over 20 years of continuous downtown investment, we deliver integrated strategy, leasing, development, and construction to help brands thrive.",
};

export const GEO_PAGES = [
  {
    slug: "bristol-tn",
    city: "Bristol",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Bristol, TN",
    metaTitle: "Commercial Real Estate Bristol TN | Vision LLC",
    metaDescription:
      "Vision LLC is Bristol TN's largest private commercial property owner. Find office space, storefronts & warehouse space in Downtown Bristol. Call 423-573-1022.",
    heroSubline: "The #1 Commercial Property Owner in Downtown Bristol",
    lat: 36.5951,
    lng: -82.1887,
    zipCode: "37620",
    countyName: "Sullivan County",
    neighborhoods: ["Downtown Bristol", "State Street", "The Pinnacle District", "Fairmount"],
    nearbyHighways: ["I-81", "US-11E", "US-19W", "TN-394"],
    population: "43,000",
    medianIncome: "$38,000",
    keyEmployers: ["Ballad Health", "Tennessee Eastman", "Bristol Motor Speedway", "King University"],
    marketBlurb:
      "Bristol sits on the Tennessee-Virginia state line, offering businesses a rare dual-state advantage with zip code 37620. As the anchor city of the Tri-Cities MSA, Downtown Bristol is experiencing a powerful urban revival — driven by adaptive reuse, new retail, and hospitality investment along State Street and the Pinnacle District.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse", "CoWorking"],
    isPrimary: true,
  },
  {
    slug: "kingsport-tn",
    city: "Kingsport",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Kingsport, TN",
    metaTitle: "Commercial Real Estate Kingsport TN | Vision LLC",
    metaDescription:
      "Looking for commercial property in Kingsport, TN? Vision LLC serves the entire Tri-Cities region with office space, retail, and industrial properties. Call 423-573-1022.",
    heroSubline: "Commercial Property Solutions Serving Kingsport & the Tri-Cities",
    lat: 36.5484,
    lng: -82.5618,
    zipCode: "37660",
    countyName: "Sullivan County",
    neighborhoods: ["Center City", "Kingsport Town Center", "Riverview", "Eastman Road Corridor"],
    nearbyHighways: ["I-26", "US-11W", "TN-36", "TN-126"],
    population: "55,000",
    medianIncome: "$44,000",
    keyEmployers: ["Eastman Chemical", "Holston Valley Medical", "Domtar", "BAE Systems"],
    marketBlurb:
      "Kingsport (zip 37660) is the industrial powerhouse of the Tri-Cities, anchored by Eastman Chemical — one of the world's largest specialty chemical companies. The Center City district is undergoing major reinvention along the I-26 corridor, creating prime commercial real estate opportunities for office and retail tenants.",
    availableTypes: ["Office", "Retail Storefront", "Industrial/Warehouse"],
    isPrimary: false,
  },
  {
    slug: "johnson-city-tn",
    city: "Johnson City",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Johnson City, TN",
    metaTitle: "Commercial Real Estate Johnson City TN | Vision LLC",
    metaDescription:
      "Vision LLC offers commercial real estate solutions in Johnson City, TN. Office space, retail storefronts & more. Serving the full Tri-Cities region. Call 423-573-1022.",
    heroSubline: "Office Space & Commercial Properties Serving Johnson City",
    lat: 36.3134,
    lng: -82.3535,
    zipCode: "37601",
    countyName: "Washington County",
    neighborhoods: ["Downtown Johnson City", "State of Franklin", "University District", "North Side"],
    nearbyHighways: ["I-26", "US-321", "TN-381", "TN-67"],
    population: "71,000",
    medianIncome: "$40,000",
    keyEmployers: ["ETSU", "Ballad Health", "Domtar", "Carilion Clinic"],
    marketBlurb:
      "Johnson City (zip 37601) is the largest city in the Tri-Cities and home to East Tennessee State University. The Downtown and State of Franklin districts along I-26 are rapidly evolving — making this an ideal market for retail, professional office, and mixed-use commercial investment.",
    availableTypes: ["Office", "Retail Storefront", "Mixed-Use"],
    isPrimary: false,
  },
  {
    slug: "abingdon-va",
    city: "Abingdon",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Abingdon, VA",
    metaTitle: "Commercial Real Estate Abingdon VA | Vision LLC",
    metaDescription:
      "Commercial property in Abingdon, VA. Vision LLC serves both sides of the TN/VA state line with office, retail & development services. Call 423-573-1022.",
    heroSubline: "Virginia Commercial Real Estate — Just Across the State Line",
    lat: 36.7098,
    lng: -81.9774,
    zipCode: "24210",
    countyName: "Washington County",
    neighborhoods: ["Main Street Abingdon", "Old Town", "Downtown Abingdon", "Wolf Hills"],
    nearbyHighways: ["I-81", "US-11", "US-58A", "VA-75"],
    population: "9,200",
    medianIncome: "$48,000",
    keyEmployers: ["Virginia Highlands Community College", "Johnston Memorial Hospital", "Washington County Schools"],
    marketBlurb:
      "Abingdon (zip 24210) is the seat of Washington County, VA — a historic town just 20 minutes from Bristol on I-81. Known for the Barter Theatre and Virginia Creeper Trail, Abingdon's Main Street district offers boutique commercial real estate in one of Virginia's most charming small cities.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "elizabethton-tn",
    city: "Elizabethton",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Elizabethton, TN",
    metaTitle: "Commercial Real Estate Elizabethton TN | Vision LLC",
    metaDescription:
      "Commercial property & office space in Elizabethton, TN. Vision LLC serves all of Northeast Tennessee including Carter County. Contact us today.",
    heroSubline: "Commercial Opportunities in Carter County & Elizabethton",
    lat: 36.3487,
    lng: -82.2107,
    zipCode: "37643",
    countyName: "Carter County",
    neighborhoods: ["Downtown Elizabethton", "Riverside", "Doe River Corridor", "Hampton"],
    nearbyHighways: ["TN-91", "TN-19E", "US-321", "TN-67"],
    population: "14,000",
    medianIncome: "$35,000",
    keyEmployers: ["Elizabethton City Schools", "Sycamore Shoals Hospital", "Carter County Government"],
    marketBlurb:
      "Elizabethton (zip 37643) in Carter County offers affordable commercial real estate with immediate access to the Johnson City metro via US-321. The Doe River corridor and downtown district are attracting new dining and retail concepts seeking lower overhead while maintaining access to the broader Tri-Cities consumer base.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
  {
    slug: "gate-city-va",
    city: "Gate City",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Gate City, VA",
    metaTitle: "Commercial Real Estate Gate City VA | Vision LLC",
    metaDescription:
      "Commercial property in Gate City, VA (Scott County). Vision LLC serves Southwest Virginia businesses with office space, retail & consulting. Call 423-573-1022.",
    heroSubline: "Scott County Commercial Real Estate Near the Bristol Market",
    lat: 36.6323,
    lng: -82.5779,
    zipCode: "24251",
    countyName: "Scott County",
    neighborhoods: ["Downtown Gate City", "Duffield", "Weber City", "Clinchport"],
    nearbyHighways: ["US-23", "US-58A", "VA-71", "VA-72"],
    population: "2,200",
    medianIncome: "$32,000",
    keyEmployers: ["Scott County Schools", "Mountain Empire Community College", "Lonesome Pine Hospital"],
    marketBlurb:
      "Gate City (zip 24251) serves as the commercial hub of Scott County, VA — a growing market 35 minutes from Bristol along the US-23 corridor. With low overhead and proximity to the Tri-Cities labor pool, Gate City attracts businesses seeking affordable commercial space with strong Southwest Virginia market access.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "blountville-tn",
    city: "Blountville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Blountville, TN",
    metaTitle: "Commercial Real Estate Blountville TN | Vision LLC",
    metaDescription:
      "Commercial property near Tri-Cities Airport in Blountville, TN. Vision LLC serves Sullivan County with office & industrial space. Call 423-573-1022.",
    heroSubline: "Sullivan County Commercial Real Estate Near Tri-Cities Airport",
    lat: 36.5292,
    lng: -82.3296,
    zipCode: "37617",
    countyName: "Sullivan County",
    neighborhoods: ["Airport District", "Blountville Commons", "Tri-Cities Regional", "Old Jonesboro Road"],
    nearbyHighways: ["I-26", "I-81", "TN-394", "US-11W"],
    population: "12,000",
    medianIncome: "$42,000",
    keyEmployers: ["Tri-Cities Regional Airport", "Sullivan County Government", "NiSource / Columbia Gas"],
    marketBlurb:
      "Blountville (zip 37617) is strategically located at the I-26/I-81 interchange — the economic crossroads of the Tri-Cities. Anchored by Tri-Cities Regional Airport and Sullivan County government, this market offers prime industrial, office, and logistics commercial real estate with unmatched regional highway access.",
    availableTypes: ["Office", "Industrial/Warehouse", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "greeneville-tn",
    city: "Greeneville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Northeast Tennessee",
    h1: "Commercial Real Estate in Greeneville, TN",
    metaTitle: "Commercial Real Estate Greeneville TN | Vision LLC",
    metaDescription:
      "Commercial property in Greeneville, TN (Greene County). Vision LLC serves Northeast Tennessee with office space, retail & business consulting. Call 423-573-1022.",
    heroSubline: "Greene County Commercial Real Estate & Business Consulting",
    lat: 36.1637,
    lng: -82.8318,
    zipCode: "37743",
    countyName: "Greene County",
    neighborhoods: ["Downtown Greeneville", "Tusculum", "Camp Creek", "Five Points"],
    nearbyHighways: ["US-11E", "TN-70", "TN-351", "TN-172"],
    population: "15,000",
    medianIncome: "$37,000",
    keyEmployers: ["Tusculum University", "Laughlin Memorial Hospital", "General Shale"],
    marketBlurb:
      "Greeneville (zip 37743) is Greene County's seat of commerce — a historic city anchored by Tusculum University and a growing manufacturing sector along the US-11E corridor. Just 45 minutes from the Tri-Cities, Greeneville offers exceptional commercial real estate value for retail, office, and light industrial tenants.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
];


export const PROPERTIES = [
  {
    id: "city-centre",
    name: "City Centre Professional Suites",
    type: "Mixed-Use",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "1,200 – 18,000+",
    status: "Available",
    badge: "Featured",
    badgeColor: "green",
    image: "/property-images/commercial-city-centre-exterior.jpg",
    description:
      "City Centre Professional Suites offers unparalleled mixed-use flexibility in the heart of Downtown Bristol — premium street-level retail and customizable executive office suites spanning 1,200 to 18,000+ sqft, with dedicated private parking providing an exceptional foundation for businesses seeking a strategic presence in the Tri-Cities commercial real estate market.",
    features: ["Street-Level Retail", "Executive Suites", "Private Parking", "Downtown Location"],
    imageAlt: "City Centre mixed-use development exterior in Downtown Bristol TN",
  },
  {
    id: "bristol-cowork",
    name: "Bristol CoWork",
    type: "CoWorking",
    city: "Bristol, TN",
    address: "620 State Street, Bristol, TN",
    sqft: "5,000+",
    status: "Memberships Available",
    badge: "CoWork",
    badgeColor: "gold",
    image: "/property-images/cowork-shared-office.jpg",
    images: [
      "/property-images/cowork-shared-office.jpg",
      "/property-images/cowork-conference-room.jpg",
      "/property-images/cowork-lobby-waiting.jpg",
      "/property-images/cowork-private-office.jpg",
    ],
    description:
      "Experience modern commercial leasing at Bristol CoWork — a 5,000+ sqft facility at 620 State Street offering fully furnished private offices, dedicated desks, and equipped conference rooms with high-speed internet and all utilities included, engineered to support business growth in Bristol TN's commercial real estate market.",
    features: ["Private Offices", "Dedicated Desks", "Conference Rooms", "High-Speed Internet", "Fully Furnished"],
    imageAlt: "Bristol CoWork shared workspace at 620 State Street Bristol Tennessee",
  },
  {
    id: "the-executive",
    name: "The Executive — Premier Office Suites",
    type: "Office",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "500 – 12,000",
    status: "Available",
    badge: "Premium",
    badgeColor: "green",
    image: "/property-images/commercial-executive-entry.jpg",
    description:
      "Discover premier office suites within a meticulously restored historic building — prime Downtown Bristol commercial space ideal for professional services and law firms. The Executive features full-service amenities including a professional address and on-demand meeting rooms, with flexible lease terms from 500–12,000 sqft for businesses that demand a distinguished Tri-Cities presence.",
    features: ["Historic Building", "Full-Service Amenities", "Professional Address", "Flexible Leasing"],
    imageAlt: "The Executive premier office suite entry in Downtown Bristol TN",
  },
  {
    id: "centre-point-suites",
    name: "Centre Point Suites",
    type: "Retail / Office",
    city: "Bristol, TN",
    address: "Bristol, TN",
    sqft: "800 – 5,000",
    status: "Units Available",
    badge: "High-Traffic",
    badgeColor: "green",
    image: "/property-images/commercial-centerpoint-mall.jpg",
    images: [
      "/property-images/commercial-centerpoint-mall.jpg",
      "/property-images/commercial-centerpoint-2.jpg",
    ],
    description:
      "Centre Point Suites delivers prime Bristol TN commercial real estate along the city's highest-traffic corridor — versatile 800–5,000 sqft retail and office units with prominent storefronts, abundant parking, and exceptional signage opportunities for retail, medical, and personal service tenants targeting maximum visibility in the Tri-Cities.",
    features: ["High-Traffic Location", "Retail Storefronts", "Ample Parking", "Signage Opportunities"],
    imageAlt: "Centre Point retail and office complex in Bristol Tennessee",
  },
  {
    id: "foundation-event-facility",
    name: "Foundation Event Facility",
    type: "Event Space / Commercial",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "3,000 – 8,000",
    status: "Available",
    badge: "Unique",
    badgeColor: "gold",
    image: "/property-images/development-event-space-after.jpg",
    description:
      "The Foundation Event Facility presents a landmark historic adaptive reuse opportunity in Downtown Bristol — 3,000 to 8,000 sqft of versatile commercial and event space available for long-term lease or short-term event bookings, providing an unparalleled platform for elevated commercial ventures or high-profile events in the Tri-Cities market.",
    features: ["Historic Adaptive Reuse", "Event Space", "Commercial Lease", "Downtown Bristol"],
    imageAlt: "Foundation Event Facility historic building in Downtown Bristol TN",
  },
  {
    id: "warehouse",
    name: "Commercial Warehouse Space",
    type: "Industrial",
    city: "Bristol, TN",
    address: "Bristol, TN Metro",
    sqft: "2,000 – 25,000",
    status: "Available",
    badge: "Industrial",
    badgeColor: "gold",
    image: "/property-images/development-construction.jpg",
    description:
      "Flexible light industrial and warehouse space across the Bristol, TN metro area — 2,000 to 25,000 sqft with loading docks, high ceilings, 3-phase power, and direct highway access, ideal for distribution, light manufacturing, and contractor operations throughout the Tri-Cities region.",
    features: ["Loading Docks", "16'+ Ceilings", "Highway Access", "3-Phase Power"],
    imageAlt: "Commercial warehouse space Bristol TN industrial property",
  },
];

export const STATS = [
  { value: "20+", label: "Years in the Tri-Cities" },
  { value: "#1", label: "Largest Private CRE Owner in Downtown Bristol" },
  { value: "50+", label: "Commercial Properties Managed" },
  { value: "3", label: "Integrated Business Divisions" },
];

export const TESTIMONIALS = [
  {
    quote:
      "Vision LLC transformed our understanding of the Bristol market. Allen's team didn't just find us a space — they positioned us for long-term success in the region. Exceptional advisement.",
    author: "Regional Business Owner",
    location: "Bristol, TN",
    rating: 5,
  },
  {
    quote:
      "Bristol CoWork gave our startup the professional environment we needed without the overhead of a traditional lease. The team at Vision is genuinely invested in your success.",
    author: "Tech Startup Founder",
    location: "Tri-Cities, TN/VA",
    rating: 5,
  },
  {
    quote:
      "The executive advisement division is unlike anything I've experienced. J. Allen Hurley brings 30 years of real leadership to the table — strategy, not just platitudes.",
    author: "C-Suite Executive",
    location: "Johnson City, TN",
    rating: 5,
  },
];

export const SERVICES = [
  {
    id: "leasing",
    icon: "Building2",
    title: "Commercial Leasing",
    shortDesc: "Office, retail, warehouse & coworking across the Tri-Cities",
    description:
      "From intimate storefronts to large-format warehouse space, Vision LLC offers the most diverse commercial leasing portfolio in downtown Bristol. Our team matches tenants with the right space, the right terms, and the right market positioning.",
    bullets: [
      "Downtown office suites",
      "State Street retail storefronts",
      "Warehouse & industrial space",
      "Bristol CoWork memberships",
    ],
  },
  {
    id: "development",
    icon: "Hammer",
    title: "Development & Construction",
    shortDesc: "Adaptive reuse and ground-up commercial development",
    description:
      "Vision specializes in historic adaptive reuse — restoring Bristol's architectural heritage while creating modern, functional commercial spaces. Our vertically integrated model means we control strategy, design, construction, and leasing under one roof.",
    bullets: [
      "Historic adaptive reuse",
      "Ground-up commercial development",
      "Tenant improvement build-outs",
      "Long-term ownership & stewardship",
    ],
  },
  {
    id: "advisement",
    icon: "TrendingUp",
    title: "Executive Advisement",
    shortDesc: "Strategic leadership consulting for C-suite and corporate teams",
    description:
      "CEO J. Allen Hurley brings 30+ years of executive experience to provide unfiltered, results-driven advisement for corporations, government agencies, and emerging businesses. Not coaching — real strategy.",
    bullets: [
      "C-suite strategic consulting",
      "Corporate performance optimization",
      "Government agency advisement",
      "Leadership development",
    ],
  },
];

export const SPACE_TYPE_PAGES = [
  {
    slug: "coworking-space-bristol-tn",
    type: "CoWorking",
    propertyIds: ["bristol-cowork", "city-centre"],
    h1: "CoWorking Space in Bristol, TN",
    metaTitle: "CoWorking Space Bristol TN | Flexible Offices & Shared Workspaces | Vision LLC",
    metaDescription: "Find coworking space & shared office in Bristol, TN. Bristol CoWork at 620 State Street offers private offices, dedicated desks & conference rooms. Vision LLC — 423-573-1022.",
    tagline: "Flexible Workspace for Modern Businesses",
    accentColor: "#4ADE80",
    badge: "CoWork",
    intro: "Bristol CoWork at 620 State Street is the Tri-Cities' premier flexible workspace — engineered for startups, freelancers, remote teams, and growing businesses that need professional infrastructure without the overhead of a traditional lease.",
    benefits: [
      { icon: "⚡", title: "All-Inclusive Pricing", body: "One flat monthly rate covers utilities, internet, cleaning, and common areas. No surprise bills." },
      { icon: "🔑", title: "Month-to-Month Flexibility", body: "Scale up or down without break clauses. Grow your footprint as your team grows." },
      { icon: "📍", title: "Prime State Street Location", body: "A prestigious Bristol, TN business address at 620 State Street — the heart of Downtown." },
      { icon: "🤝", title: "Built-In Business Community", body: "Network with fellow founders, consultants, and professionals in the same space every day." },
    ],
    faqs: [
      { q: "How much does coworking space cost in Bristol, TN?", a: "Bristol CoWork by Vision LLC offers flexible membership plans starting with hot-desk access through to private fully-furnished offices. Contact us at 423-573-1022 for current pricing." },
      { q: "Does Bristol CoWork offer private offices?", a: "Yes — we offer private lockable office suites as well as dedicated desks and open coworking memberships. All options include high-speed internet, printing, and conference room access." },
      { q: "Can I use Bristol CoWork as my business address?", a: "Absolutely. All Bristol CoWork members receive a professional 620 State Street, Bristol TN business address for mail, registration, and client-facing materials." },
      { q: "Is coworking a good option for remote workers in the Tri-Cities?", a: "It's ideal. Remote workers get structure, reliable internet, a professional environment, and networking opportunities — without the cost or commitment of a private lease." },
      { q: "Do you offer day passes or trial memberships?", a: "Yes — reach out to our team at 423-573-1022 or leasing@teamvisionllc.com to arrange a tour and trial day." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/coworking-space-bristol-tn",
    geoLinks: ["bristol-tn", "kingsport-tn", "johnson-city-tn"],
  },
  {
    slug: "office-space-tri-cities-tn",
    type: "Office",
    propertyIds: ["the-executive", "city-centre", "centre-point-suites"],
    h1: "Office Space for Lease in the Tri-Cities, TN",
    metaTitle: "Office Space Tri-Cities TN | Bristol, Kingsport & Johnson City | Vision LLC",
    metaDescription: "Premium office space for lease in Bristol TN, Kingsport TN & Johnson City TN. Vision LLC manages 50+ commercial properties across the Tri-Cities. Call 423-573-1022.",
    tagline: "Professional Office Suites from 500 to 18,000+ sqft",
    accentColor: "#4ADE80",
    badge: "Office",
    intro: "From intimate 500 sqft professional suites to full-floor executive offices spanning 18,000+ sqft, Vision LLC manages the most diverse office portfolio in the Tri-Cities. Whether you're in Bristol, Kingsport, or Johnson City — we have the right space, at the right price.",
    benefits: [
      { icon: "🏛️", title: "Historic Premium Buildings", body: "Occupy a meticulously restored Downtown Bristol landmark. Brand-defining spaces that no suburban office park can match." },
      { icon: "📐", title: "Flexible Unit Sizes", body: "500 sqft to 18,000+ sqft — expand or consolidate within our portfolio as your company evolves." },
      { icon: "🅿️", title: "Dedicated Parking", body: "Multiple Vision LLC properties offer private tenant parking — a premium in Downtown Bristol's commercial core." },
      { icon: "🔧", title: "Full-Service & Gross Leases", body: "We offer modified gross leases with predictable monthly costs. No hidden fees. Real transparency." },
    ],
    faqs: [
      { q: "How much does office space cost to lease in Bristol, TN?", a: "Office lease rates in Bristol TN vary by building class, size, and amenities. Vision LLC offers competitive rates across our Downtown Bristol portfolio — contact us at 423-573-1022." },
      { q: "What is the difference between a private office and coworking?", a: "A private office is a dedicated, lockable suite under a traditional lease (typically 12–36 months). Coworking offers month-to-month flexibility in a shared environment." },
      { q: "Do you offer office space outside of Bristol, TN?", a: "Vision LLC's primary office inventory is in Downtown Bristol. We can also connect clients with space in Kingsport TN, Johnson City TN, and Abingdon VA through our regional network." },
      { q: "Are Vision LLC office spaces pet-friendly?", a: "Policies vary by building. Contact our leasing team at 423-573-1022 to discuss specific requirements." },
      { q: "Can I get a professional office address in Bristol TN without a full lease?", a: "Yes — Bristol CoWork memberships at 620 State Street include a professional business address without requiring a traditional office lease." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/office-space-tri-cities-tn",
    geoLinks: ["bristol-tn", "kingsport-tn", "johnson-city-tn"],
  },
  {
    slug: "retail-space-bristol-tn",
    type: "Retail / Office",
    propertyIds: ["centre-point-suites", "city-centre", "foundation-event-facility"],
    h1: "Retail Space for Lease in Bristol, TN",
    metaTitle: "Retail Space Bristol TN | Downtown Storefronts & High-Traffic Commercial | Vision LLC",
    metaDescription: "Retail space for lease in Bristol TN. Vision LLC offers downtown storefronts, street-level retail & high-traffic commercial units in Bristol's most sought-after locations. Call 423-573-1022.",
    tagline: "High-Visibility Storefronts in Bristol's Best Corridors",
    accentColor: "#FACC15",
    badge: "Retail",
    intro: "Bristol's retail landscape is experiencing a powerful revival — driven by new hospitality, tourism, and urban investment along State Street and the Pinnacle District. Vision LLC's street-level retail portfolio puts your brand in front of Bristol's most active commercial traffic corridors.",
    benefits: [
      { icon: "📍", title: "Downtown Location", body: "Street-level visibility in Downtown Bristol — where foot traffic, local press, and destination shoppers converge daily." },
      { icon: "🚦", title: "Highest-Traffic Corridors", body: "Centre Point Suites and City Centre sit on Bristol's most-visited commercial streets — with abundant signage opportunities." },
      { icon: "🏪", title: "800 to 18,000+ sqft", body: "Intimate boutique units to large-format anchor retail — we'll match lease size to your concept and business plan." },
      { icon: "🅿️", title: "Ample Customer Parking", body: "Dedicated tenant and customer parking at multiple Vision LLC properties — a critical advantage for retail conversion." },
    ],
    faqs: [
      { q: "Where is the best retail location in Downtown Bristol TN?", a: "State Street and the Pinnacle District are Bristol's retail hot spots. Vision LLC owns multiple properties along these corridors." },
      { q: "How much does retail space cost to lease in Bristol TN?", a: "Retail lease rates depend on location, size, and condition. Contact our leasing team at 423-573-1022 for current availability and pricing." },
      { q: "Does Vision LLC work with restaurant or food & beverage concepts?", a: "Yes — we have experience leasing to F&B concepts and can discuss build-out allowances and modified lease structures to support hospitality tenants." },
      { q: "What retail spaces are available near State Street Bristol?", a: "Vision LLC currently has street-level retail units available at City Centre Professional Suites and Centre Point Suites. Contact us to arrange a tour." },
      { q: "Can Vision LLC help me with a retail build-out in Bristol TN?", a: "Absolutely. Our vertically integrated model includes construction and tenant improvement services — making Vision LLC your single point of contact from lease to launch." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/retail-space-bristol-tn",
    geoLinks: ["bristol-tn", "johnson-city-tn"],
  },
  {
    slug: "industrial-space-tri-cities-tn",
    type: "Industrial",
    propertyIds: ["warehouse"],
    h1: "Warehouse & Industrial Space in the Tri-Cities, TN",
    metaTitle: "Warehouse & Industrial Space Tri-Cities TN | Bristol, Kingsport | Vision LLC",
    metaDescription: "Warehouse & industrial space for lease in the Tri-Cities TN. 2,000–25,000 sqft with loading docks, 3-phase power & direct I-81/I-26 highway access. Call Vision LLC: 423-573-1022.",
    tagline: "Flexible Industrial & Warehouse Space with Highway Access",
    accentColor: "#FACC15",
    badge: "Industrial",
    intro: "Vision LLC's industrial and warehouse portfolio provides flexible light industrial, distribution, and manufacturing space across the Bristol, TN metro area — with direct access to the I-81/I-26 interchange, the logistics crossroads of the entire Tri-Cities region.",
    benefits: [
      { icon: "🚛", title: "Loading Dock Access", body: "Drive-in and dock-high loading configurations available — supporting distribution, logistics, and manufacturing operations." },
      { icon: "⚡", title: "3-Phase Power Available", body: "Heavy industrial power supply for manufacturing, data, and equipment-intensive businesses." },
      { icon: "🛣️", title: "I-81 / I-26 Interchange", body: "Minutes from the region's primary highway interchange — ideal for regional distribution and supply chain operations." },
      { icon: "📐", title: "2,000 – 25,000 sqft", body: "Scalable industrial units from small contractor bays to full-scale warehouse operations — with room to grow." },
    ],
    faqs: [
      { q: "What size warehouse spaces are available in Bristol TN?", a: "Vision LLC's Commercial Warehouse Space offers flexible industrial units from 2,000 to 25,000 sqft across the Bristol TN metro area." },
      { q: "Do your industrial spaces have loading docks?", a: "Yes — our warehouse properties include dock-high and drive-in loading configurations. Contact us at 423-573-1022 to discuss specific loading requirements." },
      { q: "Is 3-phase power available in Vision LLC industrial properties?", a: "3-phase electrical service is available in qualifying units. Discuss power requirements with our leasing team during your consultation." },
      { q: "How close are you to I-81 and I-26?", a: "Our Bristol TN industrial properties have direct access to I-81 and the I-26 interchange — the primary logistics corridor for the entire Tri-Cities region." },
      { q: "Can I lease warehouse space month-to-month in the Tri-Cities?", a: "Lease terms are negotiable. Short-term and flexible warehouse leases may be available depending on inventory. Contact our team for current options." },
    ],
    canonicalUrl: "https://teamvisionllc.com/spaces/industrial-space-tri-cities-tn",
    geoLinks: ["bristol-tn", "kingsport-tn"],
  },
];
