// Central data store for Vision LLC site
// Geo pages, properties, team, and service data

export const COMPANY = {
  name: "Vision LLC",
  phone: "423-573-1022",
  phoneHref: "tel:+14235731022",
  email: "leasing@teamvisionllc.com",
  address: "100 5th St., Suite 2W",
  city: "Bristol",
  state: "TN",
  zip: "37620",
  fullAddress: "100 5th St., Suite 2W, Bristol, TN 37620",
  tagline: "Commercial Real Estate. Executive Advisement. Historic Stewardship.",
  heroLine: "Building the Tri-Cities — One Historic Block at a Time.",
  founded: "2002",
  yearsInBusiness: 20,
  about:
    "Vision LLC is the largest private commercial property owner in Downtown Bristol and an award-winning developer specializing in historic adaptive reuse. With over 20 years of continuous downtown investment, we deliver integrated strategy, leasing, development, and construction to help brands thrive.",
};

export const GEO_PAGES = [
  {
    slug: "bristol-tn",
    city: "Bristol",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Bristol, TN",
    metaTitle: "Commercial Real Estate Bristol TN | Vision LLC",
    metaDescription:
      "Vision LLC is Bristol TN's largest private commercial property owner. Find office space, storefronts & warehouse space in Downtown Bristol. Call 423-573-1022.",
    heroSubline: "The #1 Commercial Property Owner in Downtown Bristol",
    lat: 36.5951,
    lng: -82.1887,
    zipCode: "37620",
    countyName: "Sullivan County",
    neighborhoods: ["Downtown Bristol", "State Street", "The Pinnacle District", "Fairmount"],
    nearbyHighways: ["I-81", "US-11E", "US-19W", "TN-394"],
    population: "43,000",
    medianIncome: "$38,000",
    keyEmployers: ["Ballad Health", "Tennessee Eastman", "Bristol Motor Speedway", "King University"],
    marketBlurb:
      "Bristol sits on the Tennessee-Virginia state line, offering businesses a rare dual-state advantage with zip code 37620. As the anchor city of the Tri-Cities MSA, Downtown Bristol is experiencing a powerful urban revival — driven by adaptive reuse, new retail, and hospitality investment along State Street and the Pinnacle District.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse", "CoWorking"],
    isPrimary: true,
  },
  {
    slug: "kingsport-tn",
    city: "Kingsport",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Kingsport, TN",
    metaTitle: "Commercial Real Estate Kingsport TN | Vision LLC",
    metaDescription:
      "Looking for commercial property in Kingsport, TN? Vision LLC serves the entire Tri-Cities region with office space, retail, and industrial properties. Call 423-573-1022.",
    heroSubline: "Commercial Property Solutions Serving Kingsport & the Tri-Cities",
    lat: 36.5484,
    lng: -82.5618,
    zipCode: "37660",
    countyName: "Sullivan County",
    neighborhoods: ["Center City", "Kingsport Town Center", "Riverview", "Eastman Road Corridor"],
    nearbyHighways: ["I-26", "US-11W", "TN-36", "TN-126"],
    population: "55,000",
    medianIncome: "$44,000",
    keyEmployers: ["Eastman Chemical", "Holston Valley Medical", "Domtar", "BAE Systems"],
    marketBlurb:
      "Kingsport (zip 37660) is the industrial powerhouse of the Tri-Cities, anchored by Eastman Chemical — one of the world's largest specialty chemical companies. The Center City district is undergoing major reinvention along the I-26 corridor, creating prime commercial real estate opportunities for office and retail tenants.",
    availableTypes: ["Office", "Retail Storefront", "Industrial/Warehouse"],
    isPrimary: false,
  },
  {
    slug: "johnson-city-tn",
    city: "Johnson City",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Johnson City, TN",
    metaTitle: "Commercial Real Estate Johnson City TN | Vision LLC",
    metaDescription:
      "Vision LLC offers commercial real estate solutions in Johnson City, TN. Office space, retail storefronts & more. Serving the full Tri-Cities region. Call 423-573-1022.",
    heroSubline: "Office Space & Commercial Properties Serving Johnson City",
    lat: 36.3134,
    lng: -82.3535,
    zipCode: "37601",
    countyName: "Washington County",
    neighborhoods: ["Downtown Johnson City", "State of Franklin", "University District", "North Side"],
    nearbyHighways: ["I-26", "US-321", "TN-381", "TN-67"],
    population: "71,000",
    medianIncome: "$40,000",
    keyEmployers: ["ETSU", "Ballad Health", "Domtar", "Carilion Clinic"],
    marketBlurb:
      "Johnson City (zip 37601) is the largest city in the Tri-Cities and home to East Tennessee State University. The Downtown and State of Franklin districts along I-26 are rapidly evolving — making this an ideal market for retail, professional office, and mixed-use commercial investment.",
    availableTypes: ["Office", "Retail Storefront", "Mixed-Use"],
    isPrimary: false,
  },
  {
    slug: "abingdon-va",
    city: "Abingdon",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Abingdon, VA",
    metaTitle: "Commercial Real Estate Abingdon VA | Vision LLC",
    metaDescription:
      "Commercial property in Abingdon, VA. Vision LLC serves both sides of the TN/VA state line with office, retail & development services. Call 423-573-1022.",
    heroSubline: "Virginia Commercial Real Estate — Just Across the State Line",
    lat: 36.7098,
    lng: -81.9774,
    zipCode: "24210",
    countyName: "Washington County",
    neighborhoods: ["Main Street Abingdon", "Old Town", "Downtown Abingdon", "Wolf Hills"],
    nearbyHighways: ["I-81", "US-11", "US-58A", "VA-75"],
    population: "9,200",
    medianIncome: "$48,000",
    keyEmployers: ["Virginia Highlands Community College", "Johnston Memorial Hospital", "Washington County Schools"],
    marketBlurb:
      "Abingdon (zip 24210) is the seat of Washington County, VA — a historic town just 20 minutes from Bristol on I-81. Known for the Barter Theatre and Virginia Creeper Trail, Abingdon's Main Street district offers boutique commercial real estate in one of Virginia's most charming small cities.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "elizabethton-tn",
    city: "Elizabethton",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Elizabethton, TN",
    metaTitle: "Commercial Real Estate Elizabethton TN | Vision LLC",
    metaDescription:
      "Commercial property & office space in Elizabethton, TN. Vision LLC serves all of Northeast Tennessee including Carter County. Contact us today.",
    heroSubline: "Commercial Opportunities in Carter County & Elizabethton",
    lat: 36.3487,
    lng: -82.2107,
    zipCode: "37643",
    countyName: "Carter County",
    neighborhoods: ["Downtown Elizabethton", "Riverside", "Doe River Corridor", "Hampton"],
    nearbyHighways: ["TN-91", "TN-19E", "US-321", "TN-67"],
    population: "14,000",
    medianIncome: "$35,000",
    keyEmployers: ["Elizabethton City Schools", "Sycamore Shoals Hospital", "Carter County Government"],
    marketBlurb:
      "Elizabethton (zip 37643) in Carter County offers affordable commercial real estate with immediate access to the Johnson City metro via US-321. The Doe River corridor and downtown district are attracting new dining and retail concepts seeking lower overhead while maintaining access to the broader Tri-Cities consumer base.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
  {
    slug: "gate-city-va",
    city: "Gate City",
    state: "VA",
    stateFullName: "Virginia",
    region: "Southwest Virginia",
    h1: "Commercial Real Estate in Gate City, VA",
    metaTitle: "Commercial Real Estate Gate City VA | Vision LLC",
    metaDescription:
      "Commercial property in Gate City, VA (Scott County). Vision LLC serves Southwest Virginia businesses with office space, retail & consulting. Call 423-573-1022.",
    heroSubline: "Scott County Commercial Real Estate Near the Bristol Market",
    lat: 36.6323,
    lng: -82.5779,
    zipCode: "24251",
    countyName: "Scott County",
    neighborhoods: ["Downtown Gate City", "Duffield", "Weber City", "Clinchport"],
    nearbyHighways: ["US-23", "US-58A", "VA-71", "VA-72"],
    population: "2,200",
    medianIncome: "$32,000",
    keyEmployers: ["Scott County Schools", "Mountain Empire Community College", "Lonesome Pine Hospital"],
    marketBlurb:
      "Gate City (zip 24251) serves as the commercial hub of Scott County, VA — a growing market 35 minutes from Bristol along the US-23 corridor. With low overhead and proximity to the Tri-Cities labor pool, Gate City attracts businesses seeking affordable commercial space with strong Southwest Virginia market access.",
    availableTypes: ["Office", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "blountville-tn",
    city: "Blountville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Tri-Cities",
    h1: "Commercial Real Estate in Blountville, TN",
    metaTitle: "Commercial Real Estate Blountville TN | Vision LLC",
    metaDescription:
      "Commercial property near Tri-Cities Airport in Blountville, TN. Vision LLC serves Sullivan County with office & industrial space. Call 423-573-1022.",
    heroSubline: "Sullivan County Commercial Real Estate Near Tri-Cities Airport",
    lat: 36.5292,
    lng: -82.3296,
    zipCode: "37617",
    countyName: "Sullivan County",
    neighborhoods: ["Airport District", "Blountville Commons", "Tri-Cities Regional", "Old Jonesboro Road"],
    nearbyHighways: ["I-26", "I-81", "TN-394", "US-11W"],
    population: "12,000",
    medianIncome: "$42,000",
    keyEmployers: ["Tri-Cities Regional Airport", "Sullivan County Government", "NiSource / Columbia Gas"],
    marketBlurb:
      "Blountville (zip 37617) is strategically located at the I-26/I-81 interchange — the economic crossroads of the Tri-Cities. Anchored by Tri-Cities Regional Airport and Sullivan County government, this market offers prime industrial, office, and logistics commercial real estate with unmatched regional highway access.",
    availableTypes: ["Office", "Industrial/Warehouse", "Retail Storefront"],
    isPrimary: false,
  },
  {
    slug: "greeneville-tn",
    city: "Greeneville",
    state: "TN",
    stateFullName: "Tennessee",
    region: "Northeast Tennessee",
    h1: "Commercial Real Estate in Greeneville, TN",
    metaTitle: "Commercial Real Estate Greeneville TN | Vision LLC",
    metaDescription:
      "Commercial property in Greeneville, TN (Greene County). Vision LLC serves Northeast Tennessee with office space, retail & business consulting. Call 423-573-1022.",
    heroSubline: "Greene County Commercial Real Estate & Business Consulting",
    lat: 36.1637,
    lng: -82.8318,
    zipCode: "37743",
    countyName: "Greene County",
    neighborhoods: ["Downtown Greeneville", "Tusculum", "Camp Creek", "Five Points"],
    nearbyHighways: ["US-11E", "TN-70", "TN-351", "TN-172"],
    population: "15,000",
    medianIncome: "$37,000",
    keyEmployers: ["Tusculum University", "Laughlin Memorial Hospital", "General Shale"],
    marketBlurb:
      "Greeneville (zip 37743) is Greene County's seat of commerce — a historic city anchored by Tusculum University and a growing manufacturing sector along the US-11E corridor. Just 45 minutes from the Tri-Cities, Greeneville offers exceptional commercial real estate value for retail, office, and light industrial tenants.",
    availableTypes: ["Office", "Retail Storefront", "Warehouse"],
    isPrimary: false,
  },
];


export const PROPERTIES = [
  {
    id: "city-centre",
    name: "City Centre Professional Suites",
    type: "Mixed-Use",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "1,200 – 18,000+",
    status: "Available",
    badge: "Featured",
    badgeColor: "green",
    image: "/property-images/commercial-city-centre-exterior.jpg",
    description:
      "City Centre Professional Suites offers unparalleled mixed-use flexibility in the heart of Downtown Bristol — premium street-level retail and customizable executive office suites spanning 1,200 to 18,000+ sqft, with dedicated private parking providing an exceptional foundation for businesses seeking a strategic presence in the Tri-Cities commercial real estate market.",
    features: ["Street-Level Retail", "Executive Suites", "Private Parking", "Downtown Location"],
    imageAlt: "City Centre mixed-use development exterior in Downtown Bristol TN",
  },
  {
    id: "bristol-cowork",
    name: "Bristol CoWork",
    type: "CoWorking",
    city: "Bristol, TN",
    address: "620 State Street, Bristol, TN",
    sqft: "5,000+",
    status: "Memberships Available",
    badge: "CoWork",
    badgeColor: "gold",
    image: "/property-images/cowork-shared-office.jpg",
    images: [
      "/property-images/cowork-shared-office.jpg",
      "/property-images/cowork-conference-room.jpg",
      "/property-images/cowork-lobby-waiting.jpg",
      "/property-images/cowork-private-office.jpg",
    ],
    description:
      "Experience modern commercial leasing at Bristol CoWork — a 5,000+ sqft facility at 620 State Street offering fully furnished private offices, dedicated desks, and equipped conference rooms with high-speed internet and all utilities included, engineered to support business growth in Bristol TN's commercial real estate market.",
    features: ["Private Offices", "Dedicated Desks", "Conference Rooms", "High-Speed Internet", "Fully Furnished"],
    imageAlt: "Bristol CoWork shared workspace at 620 State Street Bristol Tennessee",
  },
  {
    id: "the-executive",
    name: "The Executive — Premier Office Suites",
    type: "Office",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "500 – 12,000",
    status: "Available",
    badge: "Premium",
    badgeColor: "green",
    image: "/property-images/commercial-executive-entry.jpg",
    description:
      "Discover premier office suites within a meticulously restored historic building — prime Downtown Bristol commercial space ideal for professional services and law firms. The Executive features full-service amenities including a professional address and on-demand meeting rooms, with flexible lease terms from 500–12,000 sqft for businesses that demand a distinguished Tri-Cities presence.",
    features: ["Historic Building", "Full-Service Amenities", "Professional Address", "Flexible Leasing"],
    imageAlt: "The Executive premier office suite entry in Downtown Bristol TN",
  },
  {
    id: "centre-point-suites",
    name: "Centre Point Suites",
    type: "Retail / Office",
    city: "Bristol, TN",
    address: "Bristol, TN",
    sqft: "800 – 5,000",
    status: "Units Available",
    badge: "High-Traffic",
    badgeColor: "green",
    image: "/property-images/commercial-centerpoint-mall.jpg",
    images: [
      "/property-images/commercial-centerpoint-mall.jpg",
      "/property-images/commercial-centerpoint-2.jpg",
    ],
    description:
      "Centre Point Suites delivers prime Bristol TN commercial real estate along the city's highest-traffic corridor — versatile 800–5,000 sqft retail and office units with prominent storefronts, abundant parking, and exceptional signage opportunities for retail, medical, and personal service tenants targeting maximum visibility in the Tri-Cities.",
    features: ["High-Traffic Location", "Retail Storefronts", "Ample Parking", "Signage Opportunities"],
    imageAlt: "Centre Point retail and office complex in Bristol Tennessee",
  },
  {
    id: "foundation-event-facility",
    name: "Foundation Event Facility",
    type: "Event Space / Commercial",
    city: "Bristol, TN",
    address: "Downtown Bristol, TN",
    sqft: "3,000 – 8,000",
    status: "Available",
    badge: "Unique",
    badgeColor: "gold",
    image: "/property-images/development-event-space-after.jpg",
    description:
      "The Foundation Event Facility presents a landmark historic adaptive reuse opportunity in Downtown Bristol — 3,000 to 8,000 sqft of versatile commercial and event space available for long-term lease or short-term event bookings, providing an unparalleled platform for elevated commercial ventures or high-profile events in the Tri-Cities market.",
    features: ["Historic Adaptive Reuse", "Event Space", "Commercial Lease", "Downtown Bristol"],
    imageAlt: "Foundation Event Facility historic building in Downtown Bristol TN",
  },
  {
    id: "warehouse",
    name: "Commercial Warehouse Space",
    type: "Industrial",
    city: "Bristol, TN",
    address: "Bristol, TN Metro",
    sqft: "2,000 – 25,000",
    status: "Available",
    badge: "Industrial",
    badgeColor: "gold",
    image: "/property-images/development-construction.jpg",
    description:
      "Flexible light industrial and warehouse space across the Bristol, TN metro area — 2,000 to 25,000 sqft with loading docks, high ceilings, 3-phase power, and direct highway access, ideal for distribution, light manufacturing, and contractor operations throughout the Tri-Cities region.",
    features: ["Loading Docks", "16'+ Ceilings", "Highway Access", "3-Phase Power"],
    imageAlt: "Commercial warehouse space Bristol TN industrial property",
  },
];

export const STATS = [
  { value: "20+", label: "Years in the Tri-Cities" },
  { value: "#1", label: "Largest Private CRE Owner in Downtown Bristol" },
  { value: "50+", label: "Commercial Properties Managed" },
  { value: "3", label: "Integrated Business Divisions" },
];

export const TESTIMONIALS = [
  {
    quote:
      "Vision LLC transformed our understanding of the Bristol market. Allen's team didn't just find us a space — they positioned us for long-term success in the region. Exceptional advisement.",
    author: "Regional Business Owner",
    location: "Bristol, TN",
    rating: 5,
  },
  {
    quote:
      "Bristol CoWork gave our startup the professional environment we needed without the overhead of a traditional lease. The team at Vision is genuinely invested in your success.",
    author: "Tech Startup Founder",
    location: "Tri-Cities, TN/VA",
    rating: 5,
  },
  {
    quote:
      "The executive advisement division is unlike anything I've experienced. J. Allen Hurley brings 30 years of real leadership to the table — strategy, not just platitudes.",
    author: "C-Suite Executive",
    location: "Johnson City, TN",
    rating: 5,
  },
];

export const SERVICES = [
  {
    id: "leasing",
    icon: "Building2",
    title: "Commercial Leasing",
    shortDesc: "Office, retail, warehouse & coworking across the Tri-Cities",
    description:
      "From intimate storefronts to large-format warehouse space, Vision LLC offers the most diverse commercial leasing portfolio in downtown Bristol. Our team matches tenants with the right space, the right terms, and the right market positioning.",
    bullets: [
      "Downtown office suites",
      "State Street retail storefronts",
      "Warehouse & industrial space",
      "Bristol CoWork memberships",
    ],
  },
  {
    id: "development",
    icon: "Hammer",
    title: "Development & Construction",
    shortDesc: "Adaptive reuse and ground-up commercial development",
    description:
      "Vision specializes in historic adaptive reuse — restoring Bristol's architectural heritage while creating modern, functional commercial spaces. Our vertically integrated model means we control strategy, design, construction, and leasing under one roof.",
    bullets: [
      "Historic adaptive reuse",
      "Ground-up commercial development",
      "Tenant improvement build-outs",
      "Long-term ownership & stewardship",
    ],
  },
  {
    id: "advisement",
    icon: "TrendingUp",
    title: "Executive Advisement",
    shortDesc: "Strategic leadership consulting for C-suite and corporate teams",
    description:
      "CEO J. Allen Hurley brings 30+ years of executive experience to provide unfiltered, results-driven advisement for corporations, government agencies, and emerging businesses. Not coaching — real strategy.",
    bullets: [
      "C-suite strategic consulting",
      "Corporate performance optimization",
      "Government agency advisement",
      "Leadership development",
    ],
  },
];
